### ISSUE TITLE
error in  core.script.praraphser

### ISSUE THREAD

**Issue by uschoen** [uschoen/hmc_0.9#1]
951         core.script.praraphser[13354] 0140    DEBUG call command: arguments value:{'channelName': {'getCallerObject': {'arguments': {'parameterName': 'name'}, 'function': 'getParameter'}}, 'timestamp': {'timeStampNow': {}}, 'value': {'getCallerObject': {'function': 'getValue'}}}
956         core.script.praraphser[13354] 0140    DEBUG call command: getCallerObject value:{'arguments': {'parameterName': 'name'}, 'function': 'getParameter'}
960         core.script.praraphser[13354] 0499    DEBUG call getCallerObject value:{'arguments': {'parameterName': 'name'}, 'function': 'getParameter'}
965         core.script.praraphser[13354] 0140    DEBUG call command: arguments value:{'parameterName': 'name'}
969         core.script.praraphser[13354] 0159    DEBUG find type srcipt in loop, return value:name
973         core.script.praraphser[13354] 0511    DEBUG function getParameter return value:temperature.28-011591363eff@onewire.rasp-heizung
978                 core.exception[13354] 0024 CRITICAL command timeStampNow is not supported in arguments
982         core.script.praraphser[13354] 0170 CRITICAL script error in script: command timeStampNow is not supported in arguments
986         core.script.praraphser[13354] 0140    DEBUG call command: getCallerObject value:{'function': 'getValue'}
990         core.script.praraphser[13354] 0499    DEBUG call getCallerObject value:{'function': 'getValue'}
995         core.script.praraphser[13354] 0511    DEBUG function getValue return value:52.12
999         core.script.praraphser[13354] 0211    DEBUG call core modul:mysqlStatistic@rasp-heizung function:update args:{'channelName': 'temperature.28-011591363eff@onewire.rasp-heizung', 'timestamp': None, 'value': 52.12}
004                 core.exception[13354] 0024 CRITICAL callModul function has error with arg: {'arguments': {'channelName': {'getCallerObject': {'arguments': {'parameterName': 'name'}, 'function': 'getParameter'}}, 'timestamp': {'timeStampNow': {}}, 'value': {'getCallerObject': {'function': 'getValue'}}}, 'function': {'string': 'update'}, 'modulName': {'string': 'mysqlStatistic@rasp-heizung'}}
Traceback (most recent call last):
  File "/mnt/nas01/git/github/hmc_0.9/core/script/praraphser.py", line 212, in __callModul
    value=getattr(self.core.module[modulName]['instance'], callerFunction)(**arguments)
TypeError: update() got an unexpected keyword argument 'channelName'
025                 core.exception[13354] 0024 CRITICAL unkoun errer in loop callModul function has error with arg: {'arguments': {'channelName': {'getCallerObject': {'arguments': {'parameterName': 'name'}, 'function': 'getParameter'}}, 'timestamp': {'timeStampNow': {}}, 'value': {'getCallerObject': {'function': 'getValue'}}}, 'function': {'string': 'update'}, 'modulName': {'string': 'mysqlStatistic@rasp-heizung'}}
Traceback (most recent call last):
  File "/mnt/nas01/git/github/hmc_0.9/core/script/praraphser.py", line 212, in __callModul
    value=getattr(self.core.module[modulName]['instance'], callerFunction)(**arguments)
TypeError: update() got an unexpected keyword argument 'channelName'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/nas01/git/github/hmc_0.9/core/script/praraphser.py", line 141, in __loop
    value=self.__command[command](value)
  File "/mnt/nas01/git/github/hmc_0.9/core/script/praraphser.py", line 224, in __callModul
    raise defaultError("callModul function has error with arg: %s"%(strg),True)
core.script.exception.defaultError: callModul function has error with arg: {'arguments': {'channelName': {'getCallerObject': {'arguments': {'parameterName': 'name'}, 'function': 'getParameter'}}, 'timestamp': {'timeStampNow': {}}, 'value': {'getCallerObject': {'function': 'getValue'}}}, 'function': {'string': 'update'}, 'modulName': {'string': 'mysqlStatistic@rasp-heizung'}}
040         core.script.praraphser[13354] 0110 CRITICAL error in Script: unkoun errer in loop callModul function has error with arg: {'arguments': {'channelName': {'getCallerObject': {'arguments': {'parameterName': 'name'}, 'function': 'getParameter'}}, 'timestamp': {'timeStampNow': {}}, 'value': {'getCallerObject': {'function': 'getValue'}}}, 'function': {'string': 'update'}, 'modulName': {'string': 'mysqlStatistic@rasp-heizung'}}

**Comment by uschoen** [comment]
"core.exception[13354] 0024 CRITICAL command timeStampNow is not supported in arguments"
found first issue... timeStampNow add to allowedCMD arguments.

**Comment by uschoen** [comment]
fix is in main branch
